### PR TITLE
Migrate from Husky v4 to v5

### PR DESCRIPTION
**Pull request by roblafeve**
## Description

Renovate had upgraded husky to v5 which requires a completely different configuration method.

### 👩‍🔬 Test Instructions

> _Provided by PR **Assignees**_

1. Make a change, commit—ensure that pre-commit runs
2. Attempt to push commit to remote branch—ensure that `test:ci` scripts run

## 🔎 Reviewer Checklist

> _Checked off by PR **Reviewers**_

- [ ] Merge destination is correct
- [ ] Code is correct as understood and conforms to quality standards
- [ ] Tests have been added where appropriate (unit, visual, end-to-end)
- [ ] Acceptance Criteria have been met

---

> ### Roles & Responsibilities
>
> #### 👨‍💻 Assignee
>
> - Initiator of this PR (be sure to set in GitHub UI)
> - Addresses feedback and change requests
> - Merges PR once approved (usually deletes branch unless `develop` or `release`)
>
> #### 👩‍💻 Reviewer
>
> - Invited to review PR by **Assignee** (via GitHub UI)
> - Is expected to complete a review and address followup

### CODE REVIEW

**Comment by blaketarter** [comment]
@roblafeve We may want to have a side conversation about husky v5 because it is no longer licensed as free for commercial use.

**Comment by roblafeve** [comment]
@blaketarter yeah I skimmed that and couldn't tell what the implications were, but yeah we might need to roll back to 4. Also, we should probably configure Renovate to not merge major versions automatically.

**Comment by blaketarter** [comment]
@roblafeve Rennovate should already be configured not to merge major version changes automatically, did it merge one of them?

**Comment by roblafeve** [comment]
@blaketarter I went back and looked and it very well was me who actually did the merge 😑

**Comment by roblafeve** [comment]
Yup https://github.com/cremalab/app-web/pull/635 —my fault 🤦

**Comment by roblafeve** [comment]
Ok, we can close this, then revert the version bump.

**Pull request closed without merging**
