### PR TITLE
CHANGE: `src/utils` → `src/functions`

### PR DESCRIPTION
**Pull request by roblafeve**
## Overview

I am playing around with the idea of simply categorizing all functions as just `functions` instead of `utils`. It's more generic, leaves less to the imagination when browsing the source directory, and doesn't unnecessarily restrict the scope of what kind of code can go there.

The downside—whereas `utils` could include constants and whatnot, `functions` is specific about the kind of code that it should contain. As I write this, I'm now on the fence.

I'd love thoughts about this.

## Review Checklist

- [ ] Merge destination is correct
- [ ] Tests cases have been added where appropriate (Jest, Loki, Cypress)
- [ ] Code is correct as understood and conforms to quality standards

## Testing Instructions

1. App works as it previously did
1. Generators have been updated

### CODE REVIEW

**Comment by ckhicks** [comment]
How about something like `lib` either as a flat directory or with a named dir for Crema stuffs?

**Comment by roblafeve** [comment]
Yeah, “lib” for “library” or “utils” for “utilities”—these all tend to get conflated (we’ve been using utils for a while now). My thought with functions is that its not abbreviated and it just says what they are. 

But I am still assuming this is just a place to put all the other functions (non-components) for doing all the things. It would still live at the top of ‘src/‘.

Why is naming stuff so...exciting!!!

**Comment by kileybublitz** [comment]
I understand why you initially wanted to change it, but I tend to lean more to the side of leaving it at utils or library or something similar because then it makes sense to me for it to continue to contain 'constants and whatnot'. 

I've started to get used to looking for 'constants and whatnot' there ¯\_(ツ)_/¯

**Comment by roblafeve** [comment]
@KileyAdams92 good points. Our generator (`npm run new:util`) does assume you are creating a function though. It is common to have a config directory where random constants can go...but then we start to get a lot of base-level directories and I get sad!

**Comment by ckhicks** [comment]
Can you provide an example of constants and whatnot that would exist outside of a function context? Something that didn't belong in `.env` but was global enough to be declared all on its own? I'm struggling to picture one that would deserve that treatment.

**Comment by roblafeve** [comment]
@ckhicks well, honestly I would probably prefer that someone house those in `.env`—so yeah not really a ton of examples come to my mind. I think of `utils` (or `functions`) as just functions used all over the app, converting one type to another, calculating stuff...shared logic.

**Comment by blaketarter** [comment]
@ckhicks @roblafeve I think globally shared test data would be an example of `constants` without functions.

**Comment by roblafeve** [comment]
@blaketarter good point...

**Comment by ckhicks** [comment]
Interesting. Unless that would make sense to be nested within a high-level `tests` dir, though, IMO it makes the most sense to have a grab-bag of utilities. Like a toolbox vs separate boxes for each type of tool. I think a viable alternative would be directories _within_ the util dir with separated concerns, which is kind of a blend of both approaches.

**Comment by roblafeve** [comment]
@ckhicks and you would have various "util types" (thinking from a generator standpoint)... Hmmmm 🤔

**Comment by roblafeve** [comment]
This has been a good conversation, thanks everyone for chiming in 😄. I think it's clear that the current `utils` approach still has merit. 👍

**Pull request closed without merging**
