### PR TITLE
Add `padding-line-between-statements` eslint rule

### PR DESCRIPTION
**Pull request by roblafeve**
## Description

Enables a few rules that will help contribute to project-wide consistency. This is mainly intended to add a space between test cases.

Lint error raised when line absent between multi-line expression.

### 🔗 Reference

> _Relevant links (e.g. issue, design, etc.)_

- [padding-line-between-statements](https://eslint.org/docs/latest/rules/padding-line-between-statements)

### 🖼 Demo

https://user-images.githubusercontent.com/157195/182718810-578e31d8-6e53-4b9e-891e-9e7e6ff43492.mov

---

> ### Roles & Responsibilities
>
> #### 👨‍💻 Assignee
>
> - Initiator of this PR (be sure to set in GitHub UI)
> - Addresses feedback and change requests
> - Merges PR once approved (usually deletes branch unless `develop` or `release`)
>
> #### 👩‍💻 Reviewer
>
> - Invited to review PR by **Assignee** (via GitHub UI)
> - Is expected to complete a review and address followup

### CODE REVIEW

**Comment by aaronb97** [comment]
I'm a fan of the idea, I was playing around with something similar on a secret client repo

I wonder if this is too restrictive though, for example I think this is a common pattern

```
const foo = ...
if (foo) {
  ...
}
```

would have to be

```
const foo = ...

if (foo) {
  ...
}
```

**Comment by aaronb97** [comment]
This is the configuration I had come up with
```
    'padding-line-between-statements': [
      'error',
      { blankLine: 'always', prev: 'multiline-block-like', next: '*' },
      { blankLine: 'always', prev: 'multiline-const', next: '*' },
      { blankLine: 'always', prev: 'multiline-expression', next: '*' },
    ],
```

**Comment by roblafeve** [comment]
> I wonder if this is too restrictive though...

@aaronb97 yeah, that's my concern. I think what you have and just sticking to multi-line blocks is smart and less controversial. 👍

**Comment by roblafeve** [comment]
@aaronb97 alright, this has been simplified and is mainly intended to handle a case like this:

https://user-images.githubusercontent.com/157195/182718605-61d49ab8-f195-4d12-aee9-7fef656e3bd3.mov

**Review by aaronb97 — APPROVED** [review]

**Review by luiz-chagas — APPROVED** [review]

**Pull request merged**
