### PR TITLE
Create CODEOWNERS

### PR DESCRIPTION
**Pull request by luiz-chagas**
## Description

I'm setting up a CODEOWNERS file with people that expressed interest and also trying to get @aaronb97 and @bvarberg involved even though they didn't express interest.

[CODEOWNERS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners)

> Code owners are automatically requested for review when someone opens a pull request that modifies code that they own. Code owners are not automatically requested to review draft pull requests. For more information about draft pull requests, see "[About pull requests](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests#draft-pull-requests)." When you mark a draft pull request as ready for review, code owners are automatically notified. If you convert a pull request to a draft, people who are already subscribed to notifications are not automatically unsubscribed. For more information, see "[Changing the stage of a pull request](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-stage-of-a-pull-request)."
When someone with admin or owner permissions has enabled required reviews, they also can optionally require approval from a code owner before the author can merge a pull request in the repository. For more information, see "[About protected branches](https://docs.github.com/en/github/administering-a-repository/about-protected-branches#require-pull-request-reviews-before-merging)."
If a file has a code owner, you can see who the code owner is before you open a pull request. In the repository, you can browse to the file and hover over .

### CODE REVIEW

**Comment by roblafeve** [comment]
@luiz-chagas let's add @blaketarter to the list as well. He's been involved in these efforts for years now.

**Comment by aaronb97** [comment]
💭 we probably just need to be aware that anyone who uses this template as a base will need to adjust the codeowners right off the bat

**Comment by roblafeve** [comment]
@aaronb97 ah, yeah, this might be why we haven't set them up for this project. 🤔

**Comment by blaketarter** [comment]
I wish there was a way to control what files get copied over when the Repo is used as a template..

**Comment by luiz-chagas** [comment]
> 💭 we probably just need to be aware that anyone who uses this template as a base will need to adjust the codeowners right off the bat

True, I'll leave this closed until there's a "template project ignore" kind of thing.

**Pull request closed without merging**
